[package]
name = "elite_journal"
version = "0.0.1-dev+alpha"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
edition = "2018"

[features]
with-sqlx = ["sqlx/runtime-async-std-native-tls"]
with-postgis-sqlx = ["with-sqlx", "geozero/with-wkb", "geozero/with-postgis-sqlx"]

[dependencies]
serde      = { version = "*", features = ["derive"] }
serde_json = "*"
chrono     = { version = "*", features = ["serde"] }
sqlx       = { version = "*", optional = true }
geozero    = { git = "https://github.com/georust/geozero", branch = "master" }
